---
title: 第十一章 期约与异步函数
date: 2022-06-17 08:23:10
tags: 红宝书笔记
categories: js
---

### Promise
    结束了回调地狱
<!--more-->
```js

1、期约 （Promise）
	-创建
	let p = new Promise((resolve, reject)=>{});
	
	-期约的状态
         待定（pending） 初始状态
         兑现（fulfilled，有时候也称为“解决”，resolved） resolve方法可改变状态
         拒绝（rejected）							 reject方法可改变状态
		无论为那种状态都是不可逆的
   
     -静态方法
		 Promise.resolve();//实例化一个解决期约		
		 Promise.reject(); //实例化一个拒绝期约
		静态方法可以把任何值转化为一个期约，如果参数本身就是期约，那它的行为就类似于空包装
        类似于幂等方法（执行多次，和执行一次效果一样）还能保存期约状态
        eg:
        let p = Promise.resolve(7);// Promise <fulfilled>
        p === Promise.resolve(p); // true
        p ;// Promise <fulfilled>

        【注意】，这个静态方法能够包装任何非期约值，包括错误对象，并将其转换为解决的期约。因此，也 可能导致不符合预期的行为：

		let p = Promise.resolve(new Error('foo')); 
         setTimeout(console.log, 0, p); // Promise <resolved>: Error: foo
	
    -错误捕获
		try/catch 只能在同步代码中捕获
		期约中捕获异步错误需要 Promise.prototype.catch() 方法
        
    -期约的实例方法
		1、实现 Thenable 接口
         2、Promise.prototype.then()
                接收两个函数 接收onResolved,onRejected的返回值。
                非函数参数默认忽略，不传第一个处理函数 应该传 null
                返回值为一个新的期约实例
                新期约实例基于 resolve,reject的返回值构建，如果没有显示返回值，则Promise.resolve()静默包装undefined
            var p01 = Promise.reject('resolve');
            p01.then(
                res=>{
                    console.log('res',res)
                },
                rej=>{
                    console.log('rej',rej)
                }
            )
		3、Promise.prototype.catch()
			只接收一个参数：onRejected 处理程序，相当于调用Promise.then(null, onRejected)
             返回新的期约实例
         4、Promise.prototype.finally()
			给期约添加 onFinally处理程序，无论 期约处于什么状态都会执行。
             用于添加清理代码，避免onResolved 和 onRejected 处理程序中出 现冗余代码.
             返回新的期约实例
			因为onFinally 被设计为与状态无关的方法，所以大多数情况下表现为父期约的传递
             如果返回待定期约，或者 onFinally处理程序抛出错误（显示抛出，返回拒绝期约），则返回相应期约（待定或拒绝）
            let p1 = Promise.resolve('foo'); 
            // 这里都会原样后传 
            let p2 = p1.finally(); 
            let p3 = p1.finally(() => undefined); 
            let p4 = p1.finally(() => {}); 
            let p5 = p1.finally(() => Promise.resolve()); 
            let p6 = p1.finally(() => 'bar'); 
            let p7 = p1.finally(() => Promise.resolve('bar')); 
            let p8 = p1.finally(() => Error('qux')); 

            let p9 = p1.finally(() => new Promise(() => {})); 
            let p10 = p1.finally(() => Promise.reject());
		   let p11 = p1.finally(() => { throw 'baz'; });

            setTimeout(console.log, 0, p2); // Promise <resolved>: foo
            setTimeout(console.log, 0, p3); // Promise <resolved>: foo
            setTimeout(console.log, 0, p4); // Promise <resolved>: foo
            setTimeout(console.log, 0, p5); // Promise <resolved>: foo
            setTimeout(console.log, 0, p6); // Promise <resolved>: foo
            setTimeout(console.log, 0, p7); // Promise <resolved>: foo
            setTimeout(console.log, 0, p8); // Promise <resolved>: foo

            setTimeout(console.log, 0, p9); // Promise <pending> 
            setTimeout(console.log, 0, p10); // Promise <rejected>: undefined
            setTimeout(console.log, 0, p11); // Promise <rejected>: baz
			
		5、非重入期约方法
        	当期约进入落定状态时，与该状态相关的处理程序仅仅会被 排期，而非立即执行。
            会把处理程序推入消息队列，等同步代码执行完前不会执行
			
            let p1 = Promise.resolve(); 
            p1.then(() => console.log('p1.then() onResolved')); 
            console.log('p1.then() returns'); 
            let p2 = Promise.reject(); 
            p2.then(null, () => console.log('p2.then() onRejected')); 
            console.log('p2.then() returns'); 
            let p3 = Promise.reject(); 
            p3.catch(() => console.log('p3.catch() onRejected')); 
            console.log('p3.catch() returns'); 
            let p4 = Promise.resolve(); 
            p4.finally(() => console.log('p4.finally() onFinally')); 
            console.log('p4.finally() returns'); 
            // p1.then() returns 
            // p2.then() returns 
            // p3.catch() returns 
            // p4.finally() returns 
            // p1.then() onResolved 
            // p2.then() onRejected 
            // p3.catch() onRejected 
            // p4.finally() onFinally
	
			let synchronousResolve; 
            // 创建一个期约并将解决函数保存在一个局部变量中 
            let p = new Promise((resolve) => { 
                synchronousResolve = function() { 
                    console.log('1: invoking resolve()'); 
                    resolve(); 
                    console.log('2: resolve() returns'); 
                }; 
            }); 
            p.then(() => console.log('4: then() handler executes')); 
            synchronousResolve(); 
            console.log('3: synchronousResolve() returns'); 
            // 实际的输出： 
            // 1: invoking resolve() 
            // 2: resolve() returns 
            // 3: synchronousResolve() returns 
            // 4: then() handler executes

			在这个例子中，即使期约状态变化发生在添加处理程序之后，处理程序也会等到运行的消息队列让 它出列时才会执行。

		6、临近处理程序的执行顺序
        	如果给期约添加多个处理程序，当期约变化时，相关处理程序会按照添加顺序一次执行。无论是 then()、catch()还是 finally()添加的处理程序都是如此。
		
            let p1 = Promise.resolve(); 
            let p2 = Promise.reject(); 
            p1.then(() => setTimeout(console.log, 0, 1)); 
            p1.then(() => setTimeout(console.log, 0, 2)); 
            // 1 
            // 2 
            p2.then(null, () => setTimeout(console.log, 0, 3)); 
            p2.then(null, () => setTimeout(console.log, 0, 4)); 
            // 3 
            // 4 
            p2.catch(() => setTimeout(console.log, 0, 5)); 
            p2.catch(() => setTimeout(console.log, 0, 6)); 
            // 5 
            // 6 
            p1.finally(() => setTimeout(console.log, 0, 7)); 
            p1.finally(() => setTimeout(console.log, 0, 8)); 
            // 7 
            // 8
		
		7、拒绝期约与错误处理
        	正常情况 throw 一个错误 后边的代码就不会执行 
            throw Error('foo'); 
            console.log('bar'); // 这一行不会执行

			但是，在期约中抛出错误时，因为错误实际上是从消息队列中异步抛出的，所以并不会阻止运行时 继续执行同步指令：
			Promise.reject(Error('foo')); 
             console.log('bar'); // bar

		8、Promise.all() 和 Promise.race
			将多个期约实例组合成一个期约的静态方法，
             -promise.all
				在一组期约全部解决之后在解决，但如果有一个期约拒绝则合成期约也会拒绝
             -promise.race
				返回一组期约中最先解决或最先拒绝的期约或镜像
                
 【 注意】 ES6 不支持取消期约和进度通知，一个主要原因就是这样会导致期约连锁和期约合成 过度复杂化。比如在一个期约连锁中，如果某个被其他期约依赖的期约被取消了或者发出了 通知，那么接下来应该发生什么完全说不清楚。毕竟，如果取消了 Promise.all()中的一个 期约，或者期约连锁中前面的期约发送了一个通知，那么接下来应该怎么办才比较合理呢？

 
 		9、promise.allSettled()
			返回一个在所有给定的promise已被决议或被拒绝后决议的promise，并带有一个对象数组，每个对象表示对应的promise结果。
         与promise.all 不同的是 allSettled 无论其中期约状态是 reject还是resolve 都会等全部期约解决再全部返回，不会拒绝
 
 
 /*
*一个异步可迭代队列类。使用enqueue() 添加值，
*使用 dequeue() 移除值。 dequeue() 返回一个期约，
*这意味着，值可以在入队之前出队。
*[Symbol.sayncIterator]和 next(),因而可以
*与 for/await 循环一起配合使用（这个循环在调用close()方法前不会终止）
*/

class AsyncQueue {
    constructor() {
        // 已入队尚未出队
        this.values = [];
        // 出队尚未入队
        this.resolvers = [];
        // 一旦关闭，任何值都不能入队
        this.closed = false;
    }
    // 进队
    enqueue(value) {
        if(this.closed) {
            throw new Error('AsyncQueue closed');
        }
        if(this.resolvers.length > 0) {
            // 如果这个值已经有对应的期约，则解决该期约
            const resolve = this.resolvers.shift();
            resolve(value)
        } else {
            // 否则，让它取排队
            this.values.push(value)
        }
    }
    // 出队
    dequeue() {
        if(this.value.length > 0) {
            // 如果有一个排队的值，为它返回一个解决期约
            const value = this.values.shift();
            return Promise.resolve(value);
        } else if(this.closed) {
            // 如果没有一个排队的值，而且队列已关闭
            // 返回一个解决为EOS（流终止）标记的期约
            return Promise.resolve(AsyncQueue.EOS);
            
        } else {
            // 否则，返回一个为解决的期约
            // 将解决方法排队，以便后面使用
            return new Promise(resolve=>　{this.resolvers.push(resolve)})
        }
    }
}

```

### async/awiat

```js
es8新增规范
决绝了Promise必须在.then()方法里边取值的限制

1、async
	async 关键字用于声明异步函数。这个关键字可以用在函数声明、函数表达式、箭头函数和方法上：
	异步函数任具有普通 js 函数的正常行为
        async function foo() { console.log(1); }
        foo(); 
        console.log(2); 
        // 1 
        // 2
	不过异步函数如果设置了返回值，则这个值会被 Promise.resolve() 包装到成一个期约对象，直接返沪一个期约对象也是一样的。
    
    拒绝期约的错误不会被异步函数捕获
    	
	async function foo() { 
        console.log(1); 
        throw 3;
        Promise.reject(4); 
    } 

    // Attach a rejected handler to the returned promise 
    foo().catch(console.log); 
    console.log(2); 
    // 1 
    // 2 
    // 3 
    // Uncaught (in promise): 4

2、await
	使用 await 关键字（必须在async 函数里边使用）可以暂停异步代码的执行，等待期约决绝。
	单独的 Promise.reject 不会被异步函数捕获
	
	async function foo() { 
        console.log(1); 
        await (() => { throw 3; })(); 
        await Promise.reject(4)
        console.log(5); //不会执行
    } 
	// 给返回的期约添加一个拒绝处理程序 
	foo().catch(console.log); 
	console.log(2);
	// 1
	// 2
	// 3

	异步函数的特质不会扩展到嵌套函数。因此，await 关键字也只能直接出现在异步函数的定 义中。在同步函数内部使用 await 会抛出 SyntaxError。

	要完全理解 await 关键字，必须知道它并非只是等待一个值可用那么简单。JavaScript 运行时在碰 到 await 关键字时，会记录在哪里暂停执行。等到 await 右边的值可用了，JavaScript 运行时会向消息 队列中推送一个任务，这个任务会恢复异步函数的执行。

    
    
    
实现 sleep
async function sleep(delay) { return new Promise((resolve) => setTimeout(resolve, delay)); }

//随机延迟
async function randomDelay(id) { 
    // 延迟 0~1000 毫秒 
    const delay = Math.random() * 1000; 
    return new Promise((resolve) => setTimeout(() => { 
        console.log(`${id} finished`); 
        resolve(); 
    }, delay));
}
//执行5次
async function foo() { 
    const t0 = Date.now(); 
    const promises = Array(5).fill(null).map((_, i) => randomDelay(i)); 
    for (const p of promises) { await p; } 
    console.log(`${Date.now() - t0}ms elapsed`); 
} 
foo();
//0 finished
//2 finished
//1 finished
//4 finished
//3 finished
//576ms elapsed

注意，虽然期约没有按照顺序执行，但 await 按顺序收到了每个期约的值：


3、for await 异步迭代

function getNum(num) {
    return new Promise((res,rej) => {
        setTimeout(()=> {
            res(num)
        }, num*1000)
    })
    
}
// 普通循环
for (let rs of [getNum(1), getNum(2), getNum(3)]) {
    console.log(await rs)
}
// for await 循环
for await(let rs of [getNum(1), getNum(2), getNum(3)]) {
    console.log( rs)
}
```

